### ISSUE TITLE
finalize figma mockup

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/MultiDest#48]
includes:

- landing page
- action page (where they enter inputs)
- results page

**Comment by JoshAC125** [comment]
![multidest mockup](https://user-images.githubusercontent.com/89360317/132148004-1a27dbc2-26c2-4b59-ac70-c079a917c36b.png)
 
https://www.figma.com/file/R6vNwb8UhHSw4jkCmvZJve/MultiDest-Plan?node-id=0%3A1

**Comment by jibranabsarulislam** [comment]
Nice prototype @JoshAC125 
@Jamestiu0927 @gabrielanurum-anyanwu @bobrien922 please review and leave critique for this UX prototype (i.e. ignore design, does this layout seem intuitive to a user who is seeing this for the first time?)

**Comment by jibranabsarulislam** [comment]
Bump @Jamestiu0927 @gabrielanurum-anyanwu @bobrien922
