### ISSUE TITLE
Writeup contents of the about page

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/MultiDest#61]
Include: 

- what the problem is/was
- reason for creating MultiDest
- solution/implementation
- technologies used
70-100 words, if you find yourself padding, don't worry about the word count; be concise and layman

**Comment by mostafa-damir** [comment]
Imagine you wanna go pick up your friends and head out to a local diner, but you don’t know how long it’ll take, how far it’ll be, or what route to take? That’s why we have created MultiDest; a program that allows its users to get the total time or the total distance of a person's starting to ending destinations with as many stops in between. MultiDest was made by a band of college students under the company name of It’s Saturday the program uses python and utilizes google maps to help get the data needed to find all the different routes that could be taken. 


p.s. change it as much as you want

**Comment by jibranabsarulislam** [comment]
> Imagine you wanna go pick up your friends and head out to a local diner, but you don’t know how long it’ll take, how far it’ll be, or what route to take? That’s why we have created MultiDest; a program that allows its users to get the total time or the total distance of a person's starting to ending destinations with as many stops in between. MultiDest was made by a band of college students under the company name of It’s Saturday the program uses python and utilizes google maps to help get the data needed to find all the different routes that could be taken.
> 
> p.s. change it as much as you want

Looks good, @Jamestiu0927 @JoshAC125 please note what may be missing and make any edits
