### ISSUE TITLE
Bio for "About us" page

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/MultiDest#62]
Please reply to this issue with a comment including:

- First Name
- School
- Year/Level
- Major
- Your contribution
- Card Color
- Optional: Nickname

This information will be used to create a grid in an "About us" page.

**Comment by JoshAC125** [comment]
Joshua
NJIT
3rd Year
Mechanical Engineering
Designer, Idea Generator, Manufacturer 
JayCee

**Comment by mostafa-damir** [comment]
Mostafa
NJIT
3rd Year
Computer Science
Coding, Ideas
Moose or Muss

**Comment by jibranabsarulislam** [comment]
> Mostafa
> 
> NJIT
> 
> 3rd Year
> 
> Computer Science
> 
> Coding, Ideas # pls be more specific here; what coding, what ideas?
> 
> Moose or Muss

**Comment by bobrien922** [comment]
Brendan
Temple University
Junior
Computer Science
Software Development, Logic Review
Pink

**Comment by Npuertol** [comment]
Nixon
Stevens Institute of Technology
Junior
Computer Engineering
Software Development

**Comment by gabrielanurum-anyanwu** [comment]
Gabriel Anurum - Anyanwu 
Rutgers NewBrunswick
Junior
Computer Science 
Programming (mainly java trying to learn  python and etc) , Moral Support, and Design 
Gabe

**Comment by Jamestiu0927** [comment]
James Tiu
University of North Texas
Junior
Mechanical Engineering Technology
Assist with logic implementation and hardware development
